---
version: '2.4'
services:
  dns:
    image: coredns/coredns
    restart: always
    expose:
      - '53'
      - '53/udp'
    ports:
      - '53:53'
      - '53:53/udp'
    volumes:
    - ./coredns-persistence:/root
    command: -conf /root/Corefile